//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab21.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [Required]
        [RegularExpression(@"^[A-Za-z]{3,}$", ErrorMessage = "Invalid Entry")]
        public string FirstName { get; set; }
        [Required]
        [RegularExpression(@"^[A-Za-z]{3,}$", ErrorMessage = "Invalid Entry")]
        public string LastName { get; set; }
        [Required]
        [RegularExpression(@"^[A-Za-z\s]{3,}$", ErrorMessage = "Invalid City")]
        public string City { get; set; }
        [Required]
        [RegularExpression(@"^[A-Za-z\s]{2,}$", ErrorMessage = "Invalid State")]
        public string State { get; set; }
        [Required]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Invalid Email")]
        public string Email { get; set; }
        [Required]
        [RegularExpression(@"^[0-9]{10}$", ErrorMessage = "Invalid Phone Number")]
        public string PhoneNumber { get; set; }
        [Required]
        [RegularExpression(@"^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{4,12}$", ErrorMessage = "Invalid Password. Must Have One UpperCase and One Number")]
        public string Password { get; set; }
      
        public DateTime SignUpDate { get; set; }
    }
}
